-- Question logging for the Collegesaurus AI chatbot (Supabase / Postgres).
-- Paste into the Supabase SQL editor and run. Safe to run more than once.
--
-- chat_logs already exists: the Streamlit app writes to it. The create below
-- only runs on a fresh project; the alter adds what the FastAPI service
-- (chatbot/logging_store.py) writes. Existing rows are kept.

create table if not exists public.chat_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  session_id text,
  lang text,
  question text,
  answer text,
  tool_calls jsonb,
  latency_ms integer,
  error text,
  ip text,         -- legacy: written by the Streamlit app only
  user_agent text  -- legacy: written by the Streamlit app only
);

alter table public.chat_logs
  add column if not exists turn_id uuid unique,
  add column if not exists outcome text,        -- answered | out_of_scope | busy | error | aborted
  add column if not exists sources jsonb,       -- [{title, url}] the answer cited
  add column if not exists top_score real,      -- best retrieval similarity; low = content gap?
  add column if not exists page text,           -- site page the chat was opened from
  add column if not exists model text,
  add column if not exists index_version text,  -- content_sha of the index that answered
  add column if not exists ip_hmac text;        -- keyed hash of the client IP, never the IP

-- Thumbs up / down. Insert-only and keyed by turn_id; no foreign key, because
-- feedback can arrive before the turn's log row is written.
create table if not exists public.chat_feedback (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  turn_id uuid not null,
  value smallint not null check (value in (-1, 1))
);
create index if not exists chat_feedback_turn_id_idx on public.chat_feedback (turn_id);

-- Questions worth a look when hunting for content gaps: refused as off-topic,
-- thumbed down, or answered from weak matches. 0.55 is a starting guess for
-- gemini-embedding-001 cosine scores; tune it once real questions come in.
create or replace view public.chat_gaps
with (security_invoker = true) as
select l.created_at, l.lang, l.page, l.question, l.answer, l.outcome, l.top_score, f.feedback
from public.chat_logs l
left join (
  select turn_id, min(value) as feedback from public.chat_feedback group by turn_id
) f using (turn_id)
where l.outcome = 'out_of_scope' or f.feedback = -1 or l.top_score < 0.55
order by l.created_at desc;

-- The service writes with the secret key (the service_role role). Supabase
-- stops auto-granting new public tables on 2026-10-30, so grant explicitly.
-- Logs are never readable through the public API.
grant select, insert on public.chat_logs to service_role;
grant select, insert on public.chat_feedback to service_role;
alter table public.chat_feedback enable row level security;
revoke all on public.chat_feedback from anon, authenticated;
revoke all on public.chat_gaps from anon, authenticated;

-- After the Streamlit app is retired (it inserts with the legacy anon key),
-- close chat_logs to the public roles as well:
--   alter table public.chat_logs enable row level security;
--   revoke all on public.chat_logs from anon, authenticated;
